# Generated by Django 6.0.2 on 2026-02-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='section',
            field=models.CharField(default='Unknown', max_length=25),
        ),
        migrations.AddField(
            model_name='congestion',
            name='section',
            field=models.CharField(default='Unknown', max_length=25),
        ),
    ]
