# Generated by Django 6.0.2 on 2026-05-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_accident_section_congestion_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=25)),
                ('num_cars_left', models.IntegerField(default=0)),
                ('num_cars_right', models.IntegerField(default=0)),
                ('num_cars_top', models.IntegerField(default=0)),
                ('num_cars_bottom', models.IntegerField(default=0)),
                ('total_cars', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'historic_data',
            },
        ),
    ]
