# Generated by Django 6.0.2 on 2026-05-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pushtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaxWaitTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=25)),
                ('group', models.CharField(default='Unknown', max_length=10)),
                ('max_wait_time', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'max_wait_time',
            },
        ),
    ]
